server:
  servlet:
    context-path: /ling
  port: 8093
logging:
  level:
    com.yuling.zhang: debug
    org.springframework: info
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 30MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zsx1029!@#
    url: jdbc:mysql://106.53.36.84:3306/springboot_ling?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小，最小，最大
    initialSize: 50
    minIdle: 50
    maxActive: 150
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    #设置时区
    time-zone: GMT+8

  redis:
    host: 106.53.36.84
    port: 6379
    password: redis1029!@#
    timeout: 5000
    jedis:
      pool:
        max-active: 1000
        max-wait: 60000
        max-idle: 100
        min-idle: 50

mybatis:
  mapper-locations: classpath*:mapper/*.xml     # mapper映射文件


